/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package virushostdb;

import java.awt.Graphics;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import javax.swing.JFileChooser;
import javax.swing.JPanel;

/**
 *
 * @author Administrator
 */
public class VirusHostDB extends javax.swing.JFrame {
    private final JFileChooser openFileChooser;
    public String pad;
    JPanel panel = new JPanel();

    /**
     * Creates new form NewJFrame
     */
    public VirusHostDB() {
        initComponents();
        openFileChooser = new JFileChooser();
        openFileChooser.setCurrentDirectory(new File("C:/Users/Administrator/Desktop/Bio-informatica/Leerjaar 2/Informatica/Course 6/EindViralHostDB/virushostdb.tsv"));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        FileURL = new javax.swing.JLabel();
        ViralClas = new javax.swing.JLabel();
        HostID = new javax.swing.JLabel();
        Bladerfunctie = new javax.swing.JButton();
        Openfunctie = new javax.swing.JButton();
        host1 = new javax.swing.JComboBox<>();
        host2 = new javax.swing.JComboBox<>();
        input = new javax.swing.JTextField();
        Overeenkomst = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        FileURL.setText("File of URL");

        ViralClas.setText("Viral Classification");

        HostID.setText("Host ID");

        Bladerfunctie.setText("Blader");
        Bladerfunctie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BladerfunctieActionPerformed(evt);
            }
        });

        Openfunctie.setText("Open");
        Openfunctie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OpenfunctieActionPerformed(evt);
            }
        });

        host1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        host1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                host1ActionPerformed(evt);
            }
        });

        host2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        host2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                host2ActionPerformed(evt);
            }
        });

        Overeenkomst.setBackground(new java.awt.Color(255, 204, 204));

        javax.swing.GroupLayout OvereenkomstLayout = new javax.swing.GroupLayout(Overeenkomst);
        Overeenkomst.setLayout(OvereenkomstLayout);
        OvereenkomstLayout.setHorizontalGroup(
            OvereenkomstLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 147, Short.MAX_VALUE)
        );
        OvereenkomstLayout.setVerticalGroup(
            OvereenkomstLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 110, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ViralClas)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(FileURL)
                                .addGap(65, 65, 65)
                                .addComponent(input, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(Bladerfunctie)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Openfunctie))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(HostID)
                        .addGap(92, 92, 92)
                        .addComponent(host1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(76, 76, 76)
                        .addComponent(host2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(153, 153, 153)
                        .addComponent(Overeenkomst, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(FileURL)
                            .addComponent(input, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Bladerfunctie)
                            .addComponent(Openfunctie))))
                .addGap(23, 23, 23)
                .addComponent(ViralClas)
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(HostID)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(host1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(host2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 110, Short.MAX_VALUE)
                .addComponent(Overeenkomst, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BladerfunctieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BladerfunctieActionPerformed
        // TODO add your handling code here:
        int returnValue = openFileChooser.showOpenDialog(this);
        if (returnValue == JFileChooser.APPROVE_OPTION) {
            File file = openFileChooser.getSelectedFile();
            pad = file.getPath();
            input.setText(pad);
        }
    }//GEN-LAST:event_BladerfunctieActionPerformed

    private void OpenfunctieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OpenfunctieActionPerformed
        // TODO add your handling code here:      
        
        try {
            String line;
            try (BufferedReader inFile = new BufferedReader(new FileReader(pad)) // File openen
                    ) {
                while ((line = inFile.readLine()) != null) {
                    if (!line.startsWith("#")) {
                        String[] values = line.split("\t");

                        //Pokemonsoort pokemon = new Pokemonsoort(values[0], values[1], values[3], values[4]);
                        //Pokemonsoort.add(values[0] + "\t" + values[1] + "\t" + values[3] + "\t" + values[4] + "\t");
                        //Pokemonsoort.add(pokemon);

                      
                    }

                    // regel inlezen
                    System.out.println(line + "\n"); 
                   
                }
                // Het sluiten van het bestand.
                inFile.close();
                
        } catch (FileNotFoundException fnfe) {
            System.out.println("Het bestand is niet gevonden");
        } catch (IOException ioe) {
            System.out.println("Het bestand kan niet gelezen worden");
        } catch (Exception e) {
            System.out.println("Onbekende fout: Raadpleeg een expert!");

        }
            
            //Graphics paper = VisualisatieVeld.getGraphics();
            
        }
    }//GEN-LAST:event_OpenfunctieActionPerformed

    private void host1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_host1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_host1ActionPerformed

    private void host2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_host2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_host2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VirusHostDB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VirusHostDB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VirusHostDB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VirusHostDB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VirusHostDB().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Bladerfunctie;
    private javax.swing.JLabel FileURL;
    private javax.swing.JLabel HostID;
    private javax.swing.JButton Openfunctie;
    private javax.swing.JPanel Overeenkomst;
    private javax.swing.JLabel ViralClas;
    private javax.swing.JComboBox<String> host1;
    private javax.swing.JComboBox<String> host2;
    private javax.swing.JTextField input;
    // End of variables declaration//GEN-END:variables
}
